/*
 *
 * Filters constants
 *
 */

enum ActionTypes {
  DEFAULT_ACTION = 'app/Filters/DEFAULT_ACTION',
  GET_FILTERS = 'app/Filters/GET_FILTERS',
  SET_FILTERS = 'app/Filters/SET_FILTERS',
  GET_AUTHOR_FILTERS = 'app/Filters/GET_AUTHOR_FILTERS',
  SET_AUTHOR_FILTERS = 'app/Filters/SET_AUTHOR_FILTERS',
  GET_GENRE_FILTERS = 'app/Filters/GET_GENRE_FILTERS',
  SET_GENRE_FILTERS = 'app/Filters/SET_GENRE_FILTERS',
  GET_NUMBER_OF_AWARDS_FILTERS = 'app/Filters/GET_NUMBER_OF_AWARDS_FILTER',
  SET_NUMBER_OF_AWARDS_FILTERS = 'app/Filters/SET_NUMBER_OF_AWARDS_FILTERS',
  GET_SELECTED_AUTHOR = 'app/Filters/GET_SELECTED_AUTHOR',
  SET_SELECTED_AUTHOR = 'app/Filters/SET_SELECTED_AUTHOR',
  GET_SELECTED_GENRE = 'app/Filters/GET_SELECTED_GENRE',
  SET_SELECTED_GENRE = 'app/Filters/SET_SELECTED_GENRE',
  GET_SELECTED_NUMBER_OF_AWARDS = 'app/Filters/GET_SELECTED_NUMBER_OF_AWARDS',
  SET_SELECTED_NUMBER_OF_AWARDS = 'app/Filters/SET_SELECTED_NUMBER_OF_AWARDS',
}

export default ActionTypes;
