/*
 *
 * ChartsPage constants
 *
 */

enum ActionTypes {
  DEFAULT_ACTION = "app/ChartsPage/DEFAULT_ACTION",
  GET_PRICE_DATA = "app/ChartsPage/GET_PRICE_DATA",
  SET_PRICE_DATA = "app/ChartsPage/SET_PRICE_DATA",
  GET_PROFIT_DATA = "app/ChartsPage/GET_PROFIT_DATA",
  SET_PROFIT_DATA = "app/ChartsPage/SET_PROFIT_DATA",
  GET_BEST_SELLING_GENRES_DATA = "app/ChartsPage/GET_BEST_SELLING_GENRES_DATA",
  SET_BEST_SELLING_GENRES_DATA = "app/ChartsPage/SET_BEST_SELLING_GENRES_DATA",
  GET_BEST_SELLING_BOOKS_DATA = "app/ChartsPage/GET_BEST_SELLING_BOOKS_DATA",
  SET_BEST_SELLING_BOOKS_DATA = "app/ChartsPage/SET_BEST_SELLING_BOOKS_DATA",
}

export default ActionTypes;
